baseurl = "/"
languageCode = "en"
title = "褒められもせず"
subtitle = "サブタイトル"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/ryosukemiyazawa\">Ryosuke Miyazawa</a> 2018"
#disqusShortname = "ryosukemiyazawa"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params]
subtitle = "おすすめしたいものを全力で褒める"

[permalinks]
post = "/post/:slug/"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "ryosukemiyazawa"
github = "ryosukemiyazawa"
#email = "ribice@gmail.com"
linkedin = "ryosuke.miyazawa"
facebook = "ryosuke.miyazawa"
#instagram = ""
#codepen = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
